repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.5.5
    hooks:
      - id: uv-lock

repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.8.0
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format