services:
  db: 
    image: postgres:17
    ports:
      - "5432:5432"

    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

    volumes:
      - ./.data/postgres:/var/lib/postgresql/data