# Generated by Django 5.1.2 on 2024-10-22 02:59

import common.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('lawfirm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lawsuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('men', 'Men'), ('woman', 'Woman'), ('not_informed', 'Not informed')], max_length=20)),
                ('birth_date', models.DateField()),
                ('lawfirm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawfirm.lawfirm')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.address')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawsuits.customer')),
                ('lawfirm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawfirm.lawfirm')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawsuits.customer')),
                ('document_type', models.ForeignKey(default=common.models.DocumentType.get_default, on_delete=django.db.models.deletion.SET_DEFAULT, to='common.documenttype')),
                ('lawfirm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawfirm.lawfirm')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerDocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawsuits.customerdocument')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.files')),
                ('lawfirm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawfirm.lawfirm')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawsuits.customer')),
                ('lawfirm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawfirm.lawfirm')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawsuits.customer')),
                ('lawfirm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawfirm.lawfirm')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.phone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerReferred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
                ('source', models.CharField(choices=[('website', 'Website'), ('social_network', 'Social Network'), ('lawyer_reffer', 'Lawyer Reffer'), ('customer_reffer', 'Customer Reffer')], max_length=20)),
                ('customer_refer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred', to='lawsuits.customer')),
                ('lawfirm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawfirm.lawfirm')),
                ('lawyer_refer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred', to='lawsuits.lawyer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='reffered',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lawsuits.customerreferred'),
        ),
        migrations.CreateModel(
            name='JuridicalPersonCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_reason', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=14)),
                ('name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawsuits.customer')),
                ('lawfirm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawfirm.lawfirm')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhysicalPersonCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cpf', common.models.CpfField(max_length=11)),
                ('rg', models.CharField(max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawsuits.customer')),
                ('lawfirm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawfirm.lawfirm')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
